from typing import Any

class FFmpegNormalize:
    def __init__(self, **kwargs: Any) -> None: ...
    def add_media_file(self, input_file: str, output_file: str) -> None: ...
    def run_normalization(self) -> None: ...

class FFmpegNormalizeError(Exception): ...
